# -*- coding: utf-8 -*-
"""Importing & Handling Data using Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHx45VARRZYQy94lLP0_KOIP75s8NGIl
"""

import pandas as pd

import os

data = {      "Student": ["A", "B", "C", "D", "E"],      "Math": [78, 90, 67, 95, 88],      "Science": [85, 88, 76, 92, 79],      "English": [82, 85, 80, 90, 84]  }

df = pd.DataFrame(data)

print(df)

print("\nColumn Names:")
print(df.columns)

print("\nIndex:")
print(df.index)

print("\nShape:")
print(df.shape)

print("\nFirst 3 Rows:")
print(df.head(3))

df.to_csv("students.csv", index=False)

print("Current Working Directory:")
print(os.getcwd())

df_csv = pd.read_csv("students.csv")

print("\nCSV Data:")
print(df_csv)

print("\nData Types:")
print(df_csv.dtypes)

print("\nMissing Values:")
print(df_csv.isnull().sum())

print("\nTotal Students:")
print(len(df_csv))

df.to_json("students.json", orient="records", indent=4)

df_json = pd.read_json("students.json")

print("JSON Data")
print(df_json)

print("\nComparison Between CSV and JSON")

print("""
CSV
----
• Table format
• Easy for Excel
• Less readable for nested data

JSON
-----
• Key-value format
• Human readable
• Best for APIs and web applications
""")

import sqlite3

conn = sqlite3.connect("school.db")

df.to_sql("students", conn, if_exists="replace", index=False)

sql_df = pd.read_sql("SELECT * FROM students", conn)

print(sql_df)

print("\nStudents with Math > 80")

math_students = pd.read_sql(
    "SELECT * FROM students WHERE Math > 80",
    conn
)

print(math_students)

count = pd.read_sql(
    "SELECT COUNT(*) AS Total_Students FROM students",
    conn
)

print("\nTotal Records")
print(count)

conn.close()

url = "https://www.w3schools.com/html/html_tables.asp"

tables = pd.read_html(url)

print("Total Tables Found:", len(tables))

df_web = tables[0]

print(df_web.head())

print("\nColumns")
print(df_web.columns)

print("\nNumber of Rows")
print(len(df_web))

print("\nGermany Companies")

germany = df_web[df_web["Country"] == "Germany"]

print(germany)

df_web.to_csv("companies_web.csv", index=False)

print("\nCSV Saved Successfully")

print("Mean")
print(df.mean(numeric_only=True))

print("\nMedian")
print(df.median(numeric_only=True))

print("\nMode")
print(df.mode(numeric_only=True))

print("\nVariance")
print(df.var(numeric_only=True))

print("\nStandard Deviation")
print(df.std(numeric_only=True))

# Quartiles

Q1 = df.quantile(0.25, numeric_only=True)
Q2 = df.quantile(0.50, numeric_only=True)
Q3 = df.quantile(0.75, numeric_only=True)

IQR = Q3 - Q1

print("\nQ1")
print(Q1)

print("\nQ2")
print(Q2)

print("\nQ3")
print(Q3)

print("\nIQR")
print(IQR)

# Range

range_values = df.max(numeric_only=True) - df.min(numeric_only=True)

print("\nRange")
print(range_values)

# Hardest Subject

means = df.mean(numeric_only=True)

hardest = means.idxmin()

print("\nHardest Subject")
print(hardest)

# Most Inconsistent Subject

variance = df.var(numeric_only=True)

inconsistent = variance.idxmax()

print("\nMost Inconsistent Subject")
print(inconsistent)

mean_scores = df[["Math", "Science", "English"]].mean()

above_all = df[
    (df["Math"] > mean_scores["Math"]) &
    (df["Science"] > mean_scores["Science"]) &
    (df["English"] > mean_scores["English"])
]

print("Students Above Average in All Subjects")
print(above_all)

print("\nSorted by English Marks")

print(df.sort_values(by="English", ascending=False))



print("\nAbove Average in Math Only")

math_above = df[df["Math"] > mean_scores["Math"]]

print(math_above)

# Overall Total

df["Total"] = df[["Math", "Science", "English"]].sum(axis=1)

print("\nTop 2 Students")

print(df.sort_values(by="Total", ascending=False).head(2))

import numpy as np

data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Math": [78, None, 67, 95, 88],
    "Science": [85, 88, "absent", 92, 79],
    "English": [82, 85, 80, 90, None]
}

dirty_df = pd.DataFrame(data)

print("Dirty Data")

print(dirty_df)

# Task 1

print("\nMissing Values")

print(dirty_df.isnull().sum())

# Task 2

dirty_df["Science"] = dirty_df["Science"].replace("absent", np.nan)

dirty_df["Science"] = pd.to_numeric(dirty_df["Science"])

science_mean = dirty_df["Science"].mean()

dirty_df["Science"] = dirty_df["Science"].fillna(science_mean)

# Task 3

dirty_df["Math"] = dirty_df["Math"].fillna(dirty_df["Math"].mean())

dirty_df["English"] = dirty_df["English"].fillna(dirty_df["English"].mean())

# Task 4

dirty_df["Math"] = pd.to_numeric(dirty_df["Math"])

dirty_df["Science"] = pd.to_numeric(dirty_df["Science"])

dirty_df["English"] = pd.to_numeric(dirty_df["English"])

print("\nCleaned Data")

print(dirty_df)

print("\nData Types")

print(dirty_df.dtypes)

df["Total"] = df[["Math", "Science", "English"]].sum(axis=1)

df.to_csv("processed_students.csv", index=False)

print("Processed CSV Saved Successfully")

print(df)

import matplotlib.pyplot as plt

# Total Score Bar Chart

df.plot(
    x="Student",
    y="Total",
    kind="bar",
    legend=False
)

plt.title("Total Score of Each Student")
plt.xlabel("Student")
plt.ylabel("Total Marks")

plt.show()

# -------------------------
# Highest Scoring Student
# -------------------------

highest = df.sort_values(by="Total", ascending=False).head(1)

highest.plot(
    x="Student",
    y="Total",
    kind="bar",
    legend=False
)

plt.title("Highest Scoring Student")

plt.show()

# -------------------------
# Subject Average
# -------------------------

subject_average = df[
    ["Math", "Science", "English"]
].mean()

subject_average.plot(kind="bar")

plt.title("Subject Average")

plt.ylabel("Average Marks")

plt.show()

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt


# Create Dataset


data = {
    "Student": ["A","B","C","D","E","F","G","H"],
    "Math": [72,88,65,95,80,90,55,84],
    "Science": [81,79,72,90,85,93,60,78],
    "English": [77,92,70,85,79,95,58,83],
    "Computer": [90,85,60,93,88,97,65,80]
}

df = pd.DataFrame(data)

print(df)


# Save CSV


df.to_csv("final_students.csv", index=False)

print("\nCSV Saved")


# Convert JSON


df.to_json("final_students.json", orient="records", indent=4)

print("JSON Saved")

# Store SQL

conn = sqlite3.connect("final_school.db")

df.to_sql(
    "students",
    conn,
    if_exists="replace",
    index=False
)

print("Database Saved")


# Statistics


print("\nMean")

print(df.mean(numeric_only=True))

print("\nMedian")

print(df.median(numeric_only=True))

print("\nVariance")

print(df.var(numeric_only=True))

print("\nStandard Deviation")

print(df.std(numeric_only=True))


# Total Marks


df["Total"] = df[
    ["Math","Science","English","Computer"]
].sum(axis=1)

print("\nStudent Totals")

print(df[["Student","Total"]])

# Topper


topper = df.sort_values(
    by="Total",
    ascending=False
)

print("\nTopper")

print(topper.head(1))

print("\nTop 3 Students")

print(topper.head(3))

# Plot Total Marks

df.plot(
    x="Student",
    y="Total",
    kind="bar",
    legend=False
)

plt.title("Student Total Marks")

plt.xlabel("Student")

plt.ylabel("Total Marks")

plt.show()

conn.close()